### ISSUE TITLE
Error, help pls

### ISSUE THREAD

**Issue by rsking01** [PeterHackz/BrawlStars-JavaClient#4]
>java com/haccercat/client/Main game.brawlstarsgame.com 9339

Exception in thread "main" java.lang.NoClassDefFoundError: com/haccercat/client/TcpSocket/Connection
        at com.haccercat.client.Main.main(Main.java:22)
Caused by: java.lang.ClassNotFoundException: com.haccercat.client.TcpSocket.Connection
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 1 more

**Comment by PeterHackz** [comment]
seems that you didn't compile it or didn't enter the `out` drectory
```
javac com/haccercat/client/Main.java -d out
cd out && java com/haccercat/client/Main game.brawlstarsgame.com 9339
```
